name: TechSeminar

on:
  push:

env:
  IMAGE_NAME: jamie929/spotlink:jenkins-1.0

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle Build
        run: |
          echo "âœ… Gradle ë¹Œë“œ ì‹œì‘ (í…ŒìŠ¤íŠ¸ ìƒëµ)"
          ./gradlew clean build -x test

      - name: Docker Build
        run: |
          echo "ğŸ³ Docker ì´ë¯¸ì§€ ë¹Œë“œ ì¤‘..."
          docker build -t $IMAGE_NAME .

      - name: DockerHub Login & Push
        run: |
          echo "ğŸ” DockerHub ë¡œê·¸ì¸ ì¤‘..."
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push $IMAGE_NAME
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
