name: TechSeminar
on:
  push:
env:
  IMAGE_NAME: jamie929/spotlink:jenkins-1.0
jobs:
  Git_Checkout:
    name: Git Checkout
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo "ğŸ“¥ GitHubì—ì„œ ì†ŒìŠ¤ì½”ë“œ clone ì¤‘..."
    - name: sh
      shell: bash
      run: rm -rf spotlink && git clone -b main https://github.com/jinhyunpark929/The-era-of-github-actions.git spotlink
  Gradle_Build:
    name: Gradle Build
    runs-on: ubuntu-latest
    needs: Git_Checkout
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo "âœ… Gradle ë¹Œë“œ ì‹œì‘ (í…ŒìŠ¤íŠ¸ ìƒëµ)"
    - name: sh
      shell: bash
      run: "./gradlew clean build -x test"
      working-directory: spotlink
  Docker_Build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: Gradle_Build
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo "ğŸ³ Docker ì´ë¯¸ì§€ ë¹Œë“œ ì¤‘..."
    - name: sh
      shell: bash
      run: docker build -t $IMAGE_NAME .
      working-directory: spotlink
  Docker_Login_Push:
    name: Docker Login & Push
    runs-on: ubuntu-latest
    needs: Docker_Build
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: sh
      shell: bash
      run: |
            echo "ğŸ” DockerHub ë¡œê·¸ì¸ ì¤‘..."
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME
      env:
        DOCKERHUB_USERNAME: "${{ secrets.DOCKERHUB_USERNAME }}"
        DOCKERHUB_PASSWORD: "${{ secrets.DOCKERHUB_PASSWORD }}"
